version: '3.8'
services:
  hybrid:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5499:5432'
    volumes:
      - db:/var/lib/postgresql/test
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local